apiVersion: apps/v1
kind: Deployment
metadata:
  name: ced-webpage
  namespace: ced-devops-cicd
  labels:
    app: ced-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ced-webpage
  template:
    metadata:
      labels:
        app: ced-webpage
    spec:
      containers:
        - name: ced-webpages
          image: cedrichj/devops_cicd:v2.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # Add environment variables if needed
