apiVersion: v1
kind: Service
metadata:
  name: ced-webpage
  namespace: ced-devops-cicd
spec:
  selector:
    app: ced-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

