---
- name: Install Jenkins and Maven on Ubuntu
  hosts: all
  become: yes
  vars:
    maven_version: 3.9.7
    maven_home: /opt/apache-maven-{{ maven_version }}
    maven_binary_url: https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz

  tasks:
    - name: Download Jenkins repository key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/trusted.gpg.d/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled at boot
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Download Maven
      ansible.builtin.get_url:
        url: "{{ maven_binary_url }}"
        dest: /tmp/apache-maven-{{ maven_version }}-bin.tar.gz

    - name: Extract Maven
      ansible.builtin.unarchive:
        src: /tmp/apache-maven-{{ maven_version }}-bin.tar.gz
        dest: /opt
        remote_src: yes
