---
- name: Setup K8 Control Node
  hosts: k8s-control
  become: yes
  tasks:
    - name: Configuring Hostnames
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        create: yes
      loop:
        - "192.168.0.101 k8s-control"
        - "192.168.0.102 k8s-1"
        - "192.168.0.103 k8s-2"

    - name: Ensure /etc/modules-load.d directory exists
      file:
        path: /etc/modules-load.d
        state: directory
        mode: '0755'

    - name: Preload Kernel Modules for Containerd
      lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "overlay"
        - "br_netfilter"

    - name: Load Kernel Modules
      command: modprobe "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Ensure /etc/sysctl.d/ directory exists
      file:
        path: /etc/sysctl.d
        state: directory
        mode: '0755'

    - name: Essential Kernel Module and Network Configuration for Kubernetes Setup
      lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.ipv4.ip_forward = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Install Containerd for Kubernetes
      block:
        - name: Install containerd
          apt:
            name: containerd
            state: present
            update_cache: yes

        - name: Ensure /etc/containerd/ directory exists
          file:
            path: /etc/containerd/
            state: directory
            mode: '0755'

        - name: Generate containerd default configuration
          shell: containerd config default > /etc/containerd/config.toml
          args:
            creates: /etc/containerd/config.toml

        - name: Replace SystemdCgroup value in containerd config
          replace:
            path: /etc/containerd/config.toml
            regexp: '^(\s*SystemdCgroup\s*=\s*)false'
            replace: '\1true'

        - name: Restart containerd service
          systemd:
            name: containerd
            state: restarted

    - name: Install and Set Up runc
      block:
        - name: Download runc
          get_url:
            url: https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
            dest: /tmp/runc.amd64

        - name: Install runc
          command: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

    - name: Install CNI Plugins for Kubernetes Networking
      block:
        - name: Download CNI plugins
          get_url:
            url: https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz
            dest: /tmp/cni-plugins-linux-amd64-v1.4.0.tgz

        - name: Create CNI bin directory
          file:
            path: /opt/cni/bin
            state: directory
            mode: '0755'

        - name: Extract CNI plugins
          unarchive:
            src: /tmp/cni-plugins-linux-amd64-v1.4.0.tgz
            dest: /opt/cni/bin
            remote_src: yes
            
        - name: Ensure SystemdCgroup is set to true in containerd config
          lineinfile:
            path: /etc/containerd/config.toml
            regexp: '^SystemdCgroup'
            line: 'SystemdCgroup = true'
            create: yes
            backup: yes

    - name: Install HTTPS and Certificates
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Add Kubernetes APT Repository and Keyring Setup
      block:
        - name: Create APT sources.list.d directory
          file:
            path: /etc/apt/sources.list.d
            state: directory
            mode: '0755'

        - name: Create keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download Kubernetes APT key
          get_url:
            url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
            dest: /tmp/kubernetes-apt-key
          register: apt_key

        - name: Convert Kubernetes APT key to keyring format
          command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-key
          when: apt_key.changed

        - name: Add Kubernetes APT repository
          lineinfile:
            path: /etc/apt/sources.list.d/kubernetes.list
            line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
            create: yes

    - name: Update Package Repositories
      apt:
        update_cache: yes

    - name: Turn Off Swap
      command: swapoff -a

    - name: Install Kubernetes Tools
      apt:
        name:
          - kubelet=1.29.1-1.1
          - kubeadm=1.29.1-1.1
          - kubectl=1.29.1-1.1
        state: present

    - name: Hold Kubernetes tools versions
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: fixed
